// ===== ECON_THINKERS (append, comma-separated, no trailing comma needed) =====
{ id:'econ_malthus', name:'托马斯·马尔萨斯', en:'Thomas Robert Malthus', years:'1766-1834', nationality:'英国', disc:'econ',
  bio:'英国牧师与经济学家，以《人口论》提出人口增长快于粮食供给的悲观定律。',
  keyIdeas:['人口原理','马尔萨斯陷阱','有效需求'], influence:'econ_classical',
  works:['人口原理','政治经济学原理'],
  ideas:[ {t:'人口几何增长 vs 食物算术增长', d:'人口按2、4、8倍增，粮食只能按1、2、3线性增，最终会被饥饿、瘟疫等“积极抑制”拉回。'},
          {t:'有效需求', d:'只生产不够，还得有人既有意愿又有购买力去消费，经济才循环得起来。'} ],
  wiki:'https://en.wikipedia.org/wiki/Thomas_Robert_Malthus' },
{ id:'econ_jsmill', name:'约翰·斯图亚特·穆勒', en:'John Stuart Mill', years:'1806-1873', nationality:'英国', disc:'econ',
  bio:'英国哲学家与经济学家，古典政治经济学集大成者，兼具自由主义与社会改革思想。',
  keyIdeas:['古典综合','自由放任','有限干预'], influence:'econ_classical',
  works:['政治经济学原理','论自由'],
  ideas:[ {t:'静态与动态', d:'他区分了财富如何生产（静态规律）与财富如何分配（可由社会选择），为规范经济学埋下伏笔。'},
          {t:'有限政府干预', d:'原则上支持自由市场，但认为分配问题可由社会通过制度调节。'} ],
  wiki:'https://en.wikipedia.org/wiki/John_Stuart_Mill' },
{ id:'econ_menger', name:'卡尔·门格尔', en:'Carl Menger', years:'1840-1921', nationality:'奥地利', disc:'econ',
  bio:'奥地利学派创始人，《经济学原理》开启边际革命，强调主观价值与归纳方法。',
  keyIdeas:['边际效用','主观价值','奥地利学派'], influence:'econ_austrian',
  works:['经济学原理','经济学方法论'],
  ideas:[ {t:'价值是主观的', d:'一块钻石和一杯水的价值不取决于“内在劳动”，而取决于它对具体的人有多有用。'},
          {t:'边际革命', d:'门格尔与杰文斯、瓦尔拉斯各自独立发现：决定价格的是最后一单位的边际效用。'} ],
  wiki:'https://en.wikipedia.org/wiki/Carl_Menger' },
{ id:'econ_walras', name:'里昂·瓦尔拉斯', en:'Léon Walras', years:'1834-1910', nationality:'法国', disc:'econ',
  bio:'法国经济学家，一般均衡理论奠基人，用联立方程刻画所有市场同时出清。',
  keyIdeas:['一般均衡','拍卖人','边际革命'], influence:'econ_general_eq',
  works:['纯粹经济学要义'],
  ideas:[ {t:'一般均衡', d:'整个经济是一张大网，所有商品的价格必须同时调整，才能让每个市场都供需相等。'},
          {t:'拍卖人', d:'设想一个虚拟拍卖人不断喊价、收集供求，直到找到让所有市场出清的那组价格。'} ],
  wiki:'https://en.wikipedia.org/wiki/L%C3%A9on_Walras' },
{ id:'econ_jevons', name:'威廉·斯坦利·杰文斯', en:'William Stanley Jevons', years:'1835-1882', nationality:'英国', disc:'econ',
  bio:'英国经济学家与逻辑学家，边际效用理论的奠基者之一，提出太阳黑子周期论。',
  keyIdeas:['边际效用','太阳黑子周期','煤炭终结论'], influence:'econ_marginal',
  works:['政治经济学理论','太阳黑子与贸易周期'],
  ideas:[ {t:'边际效用递减', d:'喝第一杯水解渴，第二杯还行，第十杯想吐——每多一单位带来的满足越来越小。'},
          {t:'太阳黑子与危机', d:'他大胆猜测太阳活动影响农业收成，进而触发经济周期（后被证伪，但开了用自然因素解释周期的先河）。'} ],
  wiki:'https://en.wikipedia.org/wiki/William_Stanley_Jevons' },
{ id:'econ_veblen', name:'索尔斯坦·凡勃伦', en:'Thorstein Veblen', years:'1857-1929', nationality:'美国', disc:'econ',
  bio:'美国制度经济学家，以“炫耀性消费”与“有闲阶级”犀利批判资本主义消费文化。',
  keyIdeas:['炫耀性消费','有闲阶级','制度演进'], influence:'econ_institution',
  works:['有闲阶级论','企业论'],
  ideas:[ {t:'炫耀性消费', d:'买奢侈品常常不是为了好用，而是为了向别人显示“我有钱”，消费成了地位表演。'},
          {t:'机器过程 vs 商业主义', d:'他认为真正创造财富的是工程师和工人，而“商人”只关心股价，两者利益常冲突。'} ],
  wiki:'https://en.wikipedia.org/wiki/Thorstein_Veblen' },
{ id:'econ_pigou', name:'阿瑟·塞西尔·庇古', en:'Arthur Cecil Pigou', years:'1877-1959', nationality:'英国', disc:'econ',
  bio:'英国福利经济学奠基人，马歇尔的弟子，提出用庇古税矫正外部性。',
  keyIdeas:['福利经济学','庇古税','外部性内部化'], influence:'econ_welfare',
  works:['福利经济学','失业理论'],
  ideas:[ {t:'庇古税', d:'工厂排污让别人买单，政府就对它征税，税刚好等于污染的社会成本，逼它“内部消化”。'},
          {t:'国民红利', d:'他用总国民净产品衡量社会福利，奠定了用效率与公平评价政策的框架。'} ],
  wiki:'https://en.wikipedia.org/wiki/Arthur_Cecil_Pigou' },
{ id:'econ_fisher', name:'欧文·费雪', en:'Irving Fisher', years:'1867-1947', nationality:'美国', disc:'econ',
  bio:'美国计量经济学家，货币数量论与债务-通缩理论的先驱。',
  keyIdeas:['费雪方程','债务-通缩','货币数量论'], influence:'econ_monetarism',
  works:['利息理论','货币的购买力'],
  ideas:[ {t:'费雪方程 MV=PQ', d:'货币量×流通速度=物价×产量；长期速度稳定，所以货币多了物价就涨。'},
          {t:'债务-通缩螺旋', d:'物价下跌让欠债的实际负担更重，被迫抛售资产，进一步压低物价，经济越陷越深。'} ],
  wiki:'https://en.wikipedia.org/wiki/Irving_Fisher' },
{ id:'econ_samuelson', name:'保罗·萨缪尔森', en:'Paul Samuelson', years:'1915-2009', nationality:'美国', disc:'econ',
  bio:'美国经济学家，新古典综合之父，首位诺贝尔经济学奖得主，以《经济学》教科书影响全球。',
  keyIdeas:['新古典综合','显示性偏好','乘数-加速数'], influence:'econ_neoclassical_synthesis',
  works:['经济学','经济分析基础'],
  ideas:[ {t:'新古典综合', d:'宏观用凯恩斯管需求，微观用新古典管价格，两套拼成战后主流教科书范式。'},
          {t:'显示性偏好', d:'不用问你“效用多少”，只看你“用钱买了什么”，就能反推出你的偏好。'} ],
  wiki:'https://en.wikipedia.org/wiki/Paul_Samuelson' },
{ id:'econ_arrow', name:'肯尼斯·阿罗', en:'Kenneth Arrow', years:'1921-2017', nationality:'美国', disc:'econ',
  bio:'美国经济学家，一般均衡与不可能定理的奠基人，信息经济学的先驱。',
  keyIdeas:['阿罗不可能定理','一般均衡存在','风险厌恶'], influence:'econ_general_eq',
  works:['社会选择与个人价值','一般竞争分析'],
  ideas:[ {t:'阿罗不可能定理', d:'把个人的偏好公平地加总成社会选择，同时满足几条常识条件，在数学上做不到。'},
          {t:'一般均衡存在性', d:'他和德布鲁用拓扑学严格证明了：在合适条件下，那组让所有市场出清的价格确实存在。'} ],
  wiki:'https://en.wikipedia.org/wiki/Kenneth_Arrow' },
{ id:'econ_solow', name:'罗伯特·索洛', en:'Robert Solow', years:'1924-2023', nationality:'美国', disc:'econ',
  bio:'美国经济学家，新古典增长模型缔造者，揭示长期增长主要靠技术进步。',
  keyIdeas:['索洛模型','全要素生产率','稳态'], influence:'econ_endogenous_growth',
  works:['经济增长理论贡献','资本理论与收益率'],
  ideas:[ {t:'增长靠技术不靠储蓄', d:'他的模型算出：长期人均收入增长几乎全来自“残差”——技术进步，而非多存钱。'},
          {t:'稳态', d:'投资和折旧最终会达到平衡点，人均资本不再变化，但生活水平仍在爬升（靠技术）。'} ],
  wiki:'https://en.wikipedia.org/wiki/Robert_Solow' },
{ id:'econ_nash', name:'约翰·纳什', en:'John Forbes Nash Jr.', years:'1928-2015', nationality:'美国', disc:'econ',
  bio:'美国数学家，博弈论中“纳什均衡”的提出者，诺贝尔经济学奖得主。',
  keyIdeas:['纳什均衡','非合作博弈','议价解'], influence:'econ_game',
  works:['非合作博弈','两人合作博弈'],
  ideas:[ {t:'纳什均衡', d:'当每个人都已选了对自己最好的策略、且没人能单方面改得更好时，局势就稳住了。'},
          {t:'囚徒困境的推广', d:'他的均衡概念把“个体理性导致集体糟糕”这类局面系统地形式化了。'} ],
  wiki:'https://en.wikipedia.org/wiki/John_Forbes_Nash_Jr.' },
{ id:'econ_akerlof', name:'乔治·阿克洛夫', en:'George Akerlof', years:'1940-', nationality:'美国', disc:'econ',
  bio:'美国经济学家，信息经济学先驱，以“柠檬市场”揭示信息不对称如何摧毁市场。',
  keyIdeas:['柠檬市场','信息不对称','身份经济学'], influence:'econ_info_asym',
  works:['柠檬市场','身份经济学'],
  ideas:[ {t:'柠檬市场', d:'卖车的人比买车的人更懂车况，买家怕买到劣质车只肯出均价，结果好车被挤走，市场充斥“柠檬”。'},
          {t:'信息不对称的后果', d:'当一方比另一方知道得多，市场可能失灵甚至完全消失。'} ],
  wiki:'https://en.wikipedia.org/wiki/George_Akerlof' },
{ id:'econ_stiglitz', name:'约瑟夫·斯蒂格利茨', en:'Joseph Stiglitz', years:'1943-', nationality:'美国', disc:'econ',
  bio:'美国经济学家，信息经济学与新一代凯恩斯主义代表人物，关注市场失灵与全球化公平。',
  keyIdeas:['信息经济学','市场失灵','信贷配给'], influence:'econ_info_asym,econ_new_keynesian',
  works:['信息经济学','全球化及其不满'],
  ideas:[ {t:'信息经济学', d:'他和阿克洛夫、斯彭斯证明：信息不对称会系统性地扭曲价格、工资和信贷。'},
          {t:'有效市场假说批判', d:'他认为金融市场因信息问题远非有效，需要监管来防范危机。'} ],
  wiki:'https://en.wikipedia.org/wiki/Joseph_Stiglitz' },
{ id:'econ_krugman', name:'保罗·克鲁格曼', en:'Paul Krugman', years:'1953-', nationality:'美国', disc:'econ',
  bio:'美国经济学家，新贸易理论与新经济地理学开创者，以专栏评论闻名。',
  keyIdeas:['新贸易理论','规模经济','新经济地理'], influence:'econ_new_trade',
  works:['地理与贸易','萧条经济学的回归'],
  ideas:[ {t:'规模经济驱动贸易', d:'就算两国一模一样，只要大企业靠规模降本，国家间也会专攻不同产品然后互相贸易。'},
          {t:'核心-边缘模型', d:'制造业聚集在大城市能互相降本，进一步吸走周边产业，形成中心与边缘的落差。'} ],
  wiki:'https://en.wikipedia.org/wiki/Paul_Krugman' },
{ id:'econ_piketty', name:'托马斯·皮凯蒂', en:'Thomas Piketty', years:'1971-', nationality:'法国', disc:'econ',
  bio:'法国经济学家，以《21世纪资本论》用长时段数据揭示财富不平等的回升趋势。',
  keyIdeas:['r大于g','财富集中','资本收入比'], influence:'econ_welfare',
  works:['21世纪资本论','不平等经济学'],
  ideas:[ {t:'r > g', d:'当资本回报率长期高于经济增长率，财富就会自动向已经富有的人集中。'},
          {t:'长时段数据', d:'他搜集上百年的税收数据，证明不平等并非自然消退，而会周期性回归。'} ],
  wiki:'https://en.wikipedia.org/wiki/Thomas_Piketty' },
{ id:'econ_thaler', name:'理查德·塞勒', en:'Richard Thaler', years:'1945-', nationality:'美国', disc:'econ',
  bio:'美国行为经济学家，将心理学引入经济学，提出“助推”与有限理性。',
  keyIdeas:['助推','有限理性','心理账户'], influence:'econ_behavioral',
  works:['助推','错误的行为'],
  ideas:[ {t:'心理账户', d:'人会把钱分门别类（饭钱、旅游钱），同一笔钱在不同账户里花起来痛感不同，并不“理性”。'},
          {t:'助推', d:'不改变选项自由，只把更优选项设为默认（如自动参保），就能悄悄帮人做更好的决定。'} ],
  wiki:'https://en.wikipedia.org/wiki/Richard_Thaler' }
// ===== ECON_THEORIES =====
{ id:'econ_general_eq', name:'一般均衡理论', en:'General Equilibrium Theory', era:'classical', disc:'econ',
  desc:'研究所有市场如何同时达到供需均衡的理论框架。',
  detail:'瓦尔拉斯最早用一组联立方程刻画经济中各商品与要素市场的同时出清；阿罗与德布鲁用公理化方法严格证明了均衡在合适条件下的存在性。',
  meaning:'整个经济体是一张互相牵动的网，牵一发而动全身。',
  keyThinkers:['econ_walras','econ_arrow'], concepts:['econ_supply_demand','econ_pareto','econ_perfect_comp','econ_elasticity'],
  wiki:'https://en.wikipedia.org/wiki/General_equilibrium_theory' },
{ id:'econ_welfare', name:'福利经济学', en:'Welfare Economics', era:'contemporary', disc:'econ',
  desc:'以效率与公平为标准评判资源配置优劣的经济学分支。',
  detail:'庇古开创，用社会净产品衡量总福利；帕累托效率与补偿原则成为核心工具。皮凯蒂等后来把不平等与财富集中重新拉回中心。',
  meaning:'不光看蛋糕多大，还要看切得公不公平、有没有浪费。',
  keyThinkers:['econ_pigou','econ_piketty','econ_samuelson'], concepts:['econ_pareto','econ_externality','econ_deadweight_loss','econ_public_goods','econ_gini'],
  wiki:'https://en.wikipedia.org/wiki/Welfare_economics' },
{ id:'econ_neoclassical_synthesis', name:'新古典综合', en:'Neoclassical Synthesis', era:'contemporary', disc:'econ',
  desc:'把凯恩斯宏观需求管理与新古典微观价格理论缝合的主流范式。',
  detail:'萨缪尔森在战后把两套看似矛盾的分析统一进教科书：微观靠价格信号配置资源，宏观靠政府调节有效需求。',
  meaning:'微观靠市场、宏观靠政府，各管一段。',
  keyThinkers:['econ_samuelson'], concepts:['econ_supply_demand','econ_marginal_utility','econ_rational','econ_elasticity'],
  wiki:'https://en.wikipedia.org/wiki/Neoclassical_synthesis' },
{ id:'econ_development_econ', name:'发展经济学', en:'Development Economics', era:'contemporary', disc:'econ',
  desc:'研究低收入国家如何实现经济增长与社会发展的分支。',
  detail:'关注资本积累、人力资本与制度对发展的作用；森把发展重新定义为“可行能力的扩展”，超越单纯的收入指标。',
  meaning:'穷国怎么变富，不只是钱的问题，更是能力与制度的问题。',
  keyThinkers:['econ_sen','econ_north'], concepts:['econ_human_capital','econ_gdp'],
  wiki:'https://en.wikipedia.org/wiki/Development_economics' },
{ id:'econ_endogenous_growth', name:'内生增长理论', en:'Endogenous Growth Theory', era:'contemporary', disc:'econ',
  desc:'把技术进步与知识内生于模型、解释持续增长的理论。',
  detail:'罗默与卢卡斯等指出，知识外溢和规模报酬递增能让增长自我维持，弥补了索洛模型把技术当作外生冲击的不足。',
  meaning:'增长不是天上掉下来的，而是人投资知识和技术长出来的。',
  keyThinkers:['econ_solow'], concepts:['econ_gdp','econ_human_capital','econ_economies_scale'],
  wiki:'https://en.wikipedia.org/wiki/Endogenous_growth_theory' },
{ id:'econ_new_keynesian', name:'新凯恩斯主义经济学', en:'New Keynesian Economics', era:'contemporary', disc:'econ',
  desc:'在不完全竞争与价格粘性假设下为凯恩斯结论提供微观基础的流派。',
  detail:'斯蒂格利茨、阿克洛夫等引入信息不对称与菜单成本，解释为何价格工资调不动、市场不能瞬时出清，从而需要需求管理。',
  meaning:'价格像粘牙糖，调不动，所以经济会卡在失业里。',
  keyThinkers:['econ_stiglitz','econ_akerlof','econ_krugman'], concepts:['econ_rational_expectations','econ_inflation','econ_unemployment'],
  wiki:'https://en.wikipedia.org/wiki/New_Keynesian_economics' },
{ id:'econ_new_classical', name:'新古典宏观经济学', en:'New Classical Macroeconomics', era:'contemporary', disc:'econ',
  desc:'以理性预期与市场出清为核心、强调政策长期无效的宏观流派。',
  detail:'卢卡斯等提出理性预期，认为人们会预判政策，只有未预期到的货币冲击才影响产出；长期菲利普斯曲线是垂直的。',
  meaning:'你骗不了市场，政策一旦被预料到就白忙活。',
  keyThinkers:['econ_friedman'], concepts:['econ_rational_expectations','econ_inflation','econ_unemployment'],
  wiki:'https://en.wikipedia.org/wiki/New_classical_macroeconomics' },
{ id:'econ_supply_side', name:'供给学派', en:'Supply-Side Economics', era:'contemporary', disc:'econ',
  desc:'主张通过减税与减少管制来刺激生产和投资的政策取向。',
  detail:'20世纪80年代兴起，认为高边际税率制造巨大无谓损失、压抑劳动与储蓄供给，降低税率反而能扩张税基；思想上承自古典与货币主义传统。',
  meaning:'想让经济长大，先别把干活的人税到没动力。',
  keyThinkers:['econ_friedman','econ_hayek'], concepts:['econ_deadweight_loss'],
  wiki:'https://en.wikipedia.org/wiki/Supply-side_economics' },
{ id:'econ_environmental_econ', name:'环境经济学', en:'Environmental Economics', era:'contemporary', disc:'econ',
  desc:'用经济学工具分析环境外部性与资源可持续利用的分支。',
  detail:'把污染、耗竭等外部性纳入成本收益分析，用庇古税或排污权交易内部化成本；奥斯特罗姆对公共资源治理的研究提供了制度视角。',
  meaning:'蓝天绿水也要算进账本，否则大家都会免费糟蹋。',
  keyThinkers:['econ_ostrom'], concepts:['econ_externality','econ_tragedy'],
  wiki:'https://en.wikipedia.org/wiki/Environmental_economics' },
{ id:'econ_evolutionary_econ', name:'演化经济学', en:'Evolutionary Economics', era:'structural', disc:'econ',
  desc:'把经济变迁看作类似生物演化的变异、选择过程的学派。',
  detail:'凡勃伦最早倡导以“演进”取代静态均衡；纳尔逊与温特用企业惯例与选择环境解释技术变迁，熊彼特的创造性破坏是其核心机制。',
  meaning:'经济不是一瞬间算清的，而是一代一代试错、淘汰、长出新东西。',
  keyThinkers:['econ_veblen','econ_schumpeter'], concepts:['econ_creative_destruction'],
  wiki:'https://en.wikipedia.org/wiki/Evolutionary_economics' },
{ id:'econ_new_trade', name:'新贸易理论', en:'New Trade Theory', era:'contemporary', disc:'econ',
  desc:'用规模经济与不完全竞争解释产业内贸易的理论。',
  detail:'克鲁格曼指出，即便国家间禀赋相似，企业因规模经济降本、产品差异化，也会促成同一产业内的双向贸易。',
  meaning:'不只“你种麦我产布”，连卖同类车的国家也会互相买来买去。',
  keyThinkers:['econ_krugman'], concepts:['econ_comparative_adv','econ_economies_scale'],
  wiki:'https://en.wikipedia.org/wiki/New_trade_theory' }
// ===== ECON_CONCEPTS =====
{ id:'econ_supply_demand', name:'供给与需求', en:'Supply and Demand', disc:'econ',
  desc:'决定商品价格与交易量的两支力量：卖方愿意供、买方愿意求。',
  detail:'需求随价格上升而下降，供给随价格上升而上升；二者相交之处即市场出清价格与数量。',
  example:'夏天西瓜多、买家也多，价格平稳；冬天西瓜少，价格就贵。',
  wiki:'https://en.wikipedia.org/wiki/Supply_and_demand' },
{ id:'econ_elasticity', name:'弹性', en:'Elasticity (economics)', disc:'econ',
  desc:'衡量一个量对另一个量变化敏感程度的比例指标。',
  detail:'需求价格弹性表示价格变动1%带来的需求量变动百分比；弹性大说明敏感、弹性小说明刚性强。',
  example:'胰岛素是救命药，涨价也得买，需求价格弹性很小；娱乐门票贵一点人就不去，弹性很大。',
  wiki:'https://en.wikipedia.org/wiki/Elasticity_(economics)' },
{ id:'econ_inflation', name:'通货膨胀', en:'Inflation', disc:'econ',
  desc:'一段时期内整体物价水平持续上涨、货币购买力下降的现象。',
  detail:'通常用CPI或GDP平减指数衡量；过高会扰乱预期，过低或通缩则抑制消费与投资。',
  example:'十年前一碗面10元、现在25元，同样100元能买到的东西变少了，就是通胀。',
  wiki:'https://en.wikipedia.org/wiki/Inflation' },
{ id:'econ_unemployment', name:'失业', en:'Unemployment', disc:'econ',
  desc:'有劳动能力且愿意工作的人暂时找不到工作的状态。',
  detail:'分为摩擦性、结构性、周期性等类型；自然失业率指经济正常运行时仍存在的失业底线。',
  example:'工厂因经济衰退订单减少而裁员，工人想上班却没岗，这就是周期性失业。',
  wiki:'https://en.wikipedia.org/wiki/Unemployment' },
{ id:'econ_gdp', name:'国内生产总值', en:'Gross Domestic Product', disc:'econ',
  desc:'一国在一定时期内生产的最终商品与服务的总市场价值。',
  detail:'可用生产法、收入法、支出法三种口径核算；常作为经济规模与增长的核心指标，但不反映分配与环境成本。',
  example:'一个国家一年里造的手机、提供的理发、建的桥，全部折算成钱加总，就是它的GDP。',
  wiki:'https://en.wikipedia.org/wiki/Gross_domestic_product' },
{ id:'econ_marginal_cost', name:'边际成本', en:'Marginal Cost', disc:'econ',
  desc:'每多生产一单位产品所额外增加的总成本。',
  detail:'在理性决策中，企业应把产量扩到边际成本等于边际收益为止；它常先降后升，呈U形。',
  example:'面包店多做1个面包要多的面粉和电费，就是这1个的边际成本。',
  wiki:'https://en.wikipedia.org/wiki/Marginal_cost' },
{ id:'econ_economies_scale', name:'规模经济', en:'Economies of Scale', disc:'econ',
  desc:'产量越大、平均成本越低的现象。',
  detail:'来自固定资产分摊、专业化分工与技术溢出的优势，是大型企业与国际分工的重要理由。',
  example:'汽车厂年产1万辆时每辆车成本很高，年产100万辆把厂房设备摊薄，单车成本大幅下降。',
  wiki:'https://en.wikipedia.org/wiki/Economies_of_scale' },
{ id:'econ_monopoly', name:'垄断', en:'Monopoly', disc:'econ',
  desc:'单一卖方控制市场、能影响价格的状态。',
  detail:'由于缺乏竞争，垄断者常把产量压低、价格抬高，造成无谓损失，因而成为反垄断监管的对象。',
  example:'小镇只有一家自来水公司，它说多少钱一吨你就得交多少，这就是自然垄断。',
  wiki:'https://en.wikipedia.org/wiki/Monopoly' },
{ id:'econ_perfect_comp', name:'完全竞争', en:'Perfect Competition', disc:'econ',
  desc:'无数小卖家买家、同质商品、自由进出、信息充分的理想市场结构。',
  detail:'在完全竞争中，价格等于边际成本，资源配置达到帕累托有效，是分析现实市场的基准模型。',
  example:'理想化的农贸市场，每家菜都一模一样，谁也定不了价，只能接受行情。',
  wiki:'https://en.wikipedia.org/wiki/Perfect_competition' },
{ id:'econ_consumer_surplus', name:'消费者剩余', en:'Consumer Surplus', disc:'econ',
  desc:'买家愿意付的最高价与实际付价之间的差额总和。',
  detail:'用需求曲线以下、价格以上的面积衡量，反映消费者从交易中获得的“白赚”福利。',
  example:'你最高愿花100元看电影，票价仅60元，那40元就是你的消费者剩余。',
  wiki:'https://en.wikipedia.org/wiki/Consumer_surplus' },
{ id:'econ_public_goods', name:'公共物品', en:'Public Good', disc:'econ',
  desc:'既非排他又非竞争、私人市场不愿充分提供的物品。',
  detail:'因“搭便车”问题，纯公共物品（如国防、灯塔）须由政府供给，否则会供给不足。',
  example:'小区路灯照亮所有人，没法拦谁不付钱就不能用，私人很难靠收费建它。',
  wiki:'https://en.wikipedia.org/wiki/Public_good_(economics)' },
{ id:'econ_adverse_selection', name:'逆向选择', en:'Adverse Selection', disc:'econ',
  desc:'交易前信息不对称，使“劣质方”反而更易成交的现象。',
  detail:'阿克洛夫的柠檬市场说明：买方因不知质量只肯出均价，好货退出，市场被次品充斥。',
  example:'二手车市场买家怕买到毛病车只肯低价，车况好的卖家不愿卖，留下来多是“柠檬”。',
  wiki:'https://en.wikipedia.org/wiki/Adverse_selection' },
{ id:'econ_moral_hazard', name:'道德风险', en:'Moral Hazard', disc:'econ',
  desc:'交易后因风险被转移，一方更敢冒险或放松努力的现象。',
  detail:'与逆向选择不同，它发生在签约之后；保险最典型——有了全额赔付，人可能反而不那么小心。',
  example:'车保了全险，停车就懒得锁，因为磕了有人赔——这就是道德风险。',
  wiki:'https://en.wikipedia.org/wiki/Moral_hazard' },
{ id:'econ_nash_eq', name:'纳什均衡', en:'Nash Equilibrium', disc:'econ',
  desc:'博弈中各方在给定他人策略下都不再想单方面改变策略的稳定状态。',
  detail:'由纳什提出，不要求结果对集体最优（囚徒困境即如此），却是预测互动结果的核心概念。',
  example:'两家奶茶店都选“降价”是对方不变时自己的最优，于是都降、谁也不先涨，这就是均衡。',
  wiki:'https://en.wikipedia.org/wiki/Nash_equilibrium' },
{ id:'econ_pareto', name:'帕累托效率', en:'Pareto Efficiency', disc:'econ',
  desc:'一种资源配置状态，已无法再让任何人变好而不使他人变差。',
  detail:'由帕累托提出，是福利评价的基准；现实政策常只能做“帕累托改进”式的无人受损调整。',
  example:'把闲置的公交车座位免费让站着的乘客坐，没人受损、有人受益，即一次帕累托改进。',
  wiki:'https://en.wikipedia.org/wiki/Pareto_efficiency' },
{ id:'econ_sunk_cost', name:'沉没成本', en:'Sunk Cost', disc:'econ',
  desc:'已经发生、无法收回的支出，理性决策应当忽略它。',
  detail:'“沉没成本不是成本”——做未来选择只看边际收益与边际成本，不该被过去花掉的钱绑架。',
  example:'电影看了20分钟发现是烂片，票钱已花（沉没），明智做法是立刻走，而非“看完才回本”。',
  wiki:'https://en.wikipedia.org/wiki/Sunk_cost' },
{ id:'econ_fiscal_multiplier', name:'财政乘数', en:'Fiscal Multiplier', disc:'econ',
  desc:'政府每多花一元，最终带动总产出增加的倍数。',
  detail:'凯恩斯框架下，新增支出通过收入-消费循环被放大；经济越低于充分就业，乘数往往越大。',
  example:'政府修路花100亿，工人拿工资去吃饭购物，商家再雇人，一轮轮下来GDP可能增加150亿。',
  wiki:'https://en.wikipedia.org/wiki/Fiscal_multiplier' },
{ id:'econ_human_capital', name:'人力资本', en:'Human Capital', disc:'econ',
  desc:'体现在人身上的知识、技能与健康等能提升生产力的资本。',
  detail:'贝克尔等将教育、培训、健康视为投资，其回报体现在更高收入与更快增长。',
  example:'花四年读大学虽暂缓赚钱，却换来更高的终身收入，这投入就是人力资本投资。',
  wiki:'https://en.wikipedia.org/wiki/Human_capital' },
{ id:'econ_creative_destruction', name:'创造性破坏', en:'Creative Destruction', disc:'econ',
  desc:'熊彼特提出：新创新不断淘汰旧技术旧企业的动态过程。',
  detail:'资本主义的进步正来自此——既创造新产业，也摧毁旧岗位，是增长与阵痛并存的根源。',
  example:'智能手机灭了功能机与相机胶卷厂，却催生了App与外卖配送等新行当。',
  wiki:'https://en.wikipedia.org/wiki/Creative_destruction' },
{ id:'econ_rational_expectations', name:'理性预期', en:'Rational Expectations', disc:'econ',
  desc:'人们会利用所有可得信息、无系统性偏差地预判未来经济的假设。',
  detail:'卢卡斯等据此主张：只有意外的政策冲击才短期有效，被预期到的政策长期中性。',
  example:'若大家准确预料央行要印钱通胀，就会立刻要涨价，政策刺激还没生效就被通胀吃掉。',
  wiki:'https://en.wikipedia.org/wiki/Rational_expectations' },
{ id:'econ_gini', name:'基尼系数', en:'Gini Coefficient', disc:'econ',
  desc:'衡量收入或财富分配不平等程度的0到1指标。',
  detail:'0表示完全平等、1表示一人独占；皮凯蒂等用长时段基尼揭示财富集中度周期回升。',
  example:'一个社会若10%的人拿走几乎全部收入，基尼系数就接近1，说明极度不均。',
  wiki:'https://en.wikipedia.org/wiki/Gini_coefficient' },
{ id:'econ_deadweight_loss', name:'无谓损失', en:'Deadweight Loss', disc:'econ',
  desc:'因市场失灵或税收管制，使总剩余（消费者+生产者）白白减少的部分。',
  detail:'垄断高价、税负与价格管制都会把本可成交的互利交易量挤出，造成社会福利的净损失。',
  example:'政府对每袋盐征税，买卖双方交易量减少，那部分“本来能双赢却没成”的福利就是无谓损失。',
  wiki:'https://en.wikipedia.org/wiki/Deadweight_loss' }
// ===== ECON_TOPICS =====
{ id:'econ_monetary_policy', name:'货币政策', en:'Monetary Policy', disc:'econ',
  desc:'中央银行通过调节货币供给与利率影响宏观经济的政策。',
  detail:'工具包括公开市场操作、准备金率与政策利率；目标是稳物价、促就业与金融稳定。',
  wiki:'https://en.wikipedia.org/wiki/Monetary_policy' },
{ id:'econ_fiscal_policy', name:'财政政策', en:'Fiscal Policy', disc:'econ',
  desc:'政府通过税收与支出调节总需求的宏观经济政策。',
  detail:'扩张性财政（增支减税）用于提振萧条，紧缩性则用于给过热降温；受乘数效应放大。',
  wiki:'https://en.wikipedia.org/wiki/Fiscal_policy' },
{ id:'econ_macro', name:'宏观经济学', en:'Macroeconomics', disc:'econ',
  desc:'研究整体经济的总量运行：增长、就业、物价与周期。',
  detail:'关注GDP、通胀、失业与国际收支等总量变量，以及货币与财政政策的作用。',
  wiki:'https://en.wikipedia.org/wiki/Macroeconomics' },
{ id:'econ_micro', name:'微观经济学', en:'Microeconomics', disc:'econ',
  desc:'研究个体（家庭、企业）如何在约束下做选择与互动的分支。',
  detail:'以供给需求、边际分析与一般均衡为工具，解释价格形成与资源配置。',
  wiki:'https://en.wikipedia.org/wiki/Microeconomics' },
{ id:'econ_industrial_org', name:'产业组织', en:'Industrial Organization', disc:'econ',
  desc:'研究市场结构、企业行为与绩效关系的分支。',
  detail:'围绕垄断、寡头与完全竞争的对比，分析定价、进入壁垒与反垄断政策。',
  wiki:'https://en.wikipedia.org/wiki/Industrial_organization' },
{ id:'econ_public_finance', name:'公共财政', en:'Public Finance', disc:'econ',
  desc:'研究政府收支、税收与公共品供给的经济学分支。',
  detail:'关注税收效率与公平、公共品提供与外部性矫正，是福利经济学的重要应用。',
  wiki:'https://en.wikipedia.org/wiki/Public_finance' },
{ id:'econ_development_field', name:'发展经济学（学科）', en:'Development Economics (field)', disc:'econ',
  desc:'以低收入与转型经济体的增长与社会发展为对象的学科领域。',
  detail:'综合运用增长、制度与人力资本视角，研究贫困、不平等与可持续转型。',
  wiki:'https://en.wikipedia.org/wiki/Development_economics' },
{ id:'econ_environmental_field', name:'环境经济学（学科）', en:'Environmental Economics (field)', disc:'econ',
  desc:'用经济分析处理污染、资源耗竭与气候变化的学科领域。',
  detail:'核心是把外部性内部化，并权衡当代与跨代的环境成本收益。',
  wiki:'https://en.wikipedia.org/wiki/Environmental_economics' },
{ id:'econ_health_econ', name:'卫生经济学', en:'Health Economics', disc:'econ',
  desc:'研究医疗资源如何有效与公平配置的分支。',
  detail:'涉及保险、道德风险与成本效果分析，并借重行为视角解释就医决策。',
  wiki:'https://en.wikipedia.org/wiki/Health_economics' },
{ id:'econ_behavioral_finance', name:'行为金融学', en:'Behavioral Finance', disc:'econ',
  desc:'用心理学修正“理性人”假设，解释金融市场异象的分支。',
  detail:'研究认知偏差、过度自信与羊群效应如何导致资产定价偏离有效市场。',
  wiki:'https://en.wikipedia.org/wiki/Behavioral_finance' },
{ id:'econ_banking', name:'货币银行学', en:'Money and Banking', disc:'econ',
  desc:'研究货币、银行体系与信用创造如何支撑宏观运行的分支。',
  detail:'关注存款创造、央行角色与金融中介，是货币政策运作的微观基础。',
  wiki:'https://en.wikipedia.org/wiki/Money_supply' },
{ id:'econ_taxation', name:'税收学', en:'Taxation', disc:'econ',
  desc:'研究税收设计、效率损失与公平分配的分支。',
  detail:'权衡税基宽度、税率与无谓损失，是公共财政与供给学派政策的核心议题。',
  wiki:'https://en.wikipedia.org/wiki/Taxation' }
// ===== THINKER_LINKS (append) =====
['econ_malthus','econ_smith',0.6],
['econ_malthus','econ_ricardo',0.7],
['econ_jsmill','econ_smith',0.6],
['econ_jsmill','econ_ricardo',0.6],
['econ_menger','econ_walras',0.7],
['econ_menger','econ_jevons',0.7],
['econ_walras','econ_jevons',0.6],
['econ_jevons','econ_marshall',0.6],
['econ_veblen','econ_marshall',0.4],
['econ_pigou','econ_marshall',0.7],
['econ_fisher','econ_marshall',0.5],
['econ_fisher','econ_friedman',0.6],
['econ_samuelson','econ_keynes',0.7],
['econ_samuelson','econ_hayek',0.4],
['econ_arrow','econ_samuelson',0.6],
['econ_solow','econ_samuelson',0.6],
['econ_nash','econ_arrow',0.5],
['econ_akerlof','econ_stiglitz',0.8],
['econ_akerlof','econ_sen',0.4],
['econ_stiglitz','econ_krugman',0.8],
['econ_krugman','econ_samuelson',0.5],
['econ_piketty','econ_sen',0.5]
// ===== CONCEPT_LINKS (append) =====
['econ_supply_demand','econ_elasticity',0.8],
['econ_supply_demand','econ_consumer_surplus',0.7],
['econ_supply_demand','econ_marginal_cost',0.6],
['econ_elasticity','econ_marginal_cost',0.5],
['econ_marginal_cost','econ_economies_scale',0.6],
['econ_perfect_comp','econ_monopoly',0.7],
['econ_monopoly','econ_deadweight_loss',0.7],
['econ_consumer_surplus','econ_deadweight_loss',0.6],
['econ_perfect_comp','econ_pareto',0.6],
['econ_pareto','econ_deadweight_loss',0.6],
['econ_public_goods','econ_externality',0.6],
['econ_adverse_selection','econ_signaling',0.8],
['econ_adverse_selection','econ_moral_hazard',0.8],
['econ_moral_hazard','econ_externality',0.5],
['econ_nash_eq','econ_prisoner',0.8],
['econ_nash_eq','econ_rational',0.5],
['econ_rational_expectations','econ_rational',0.6],
['econ_rational_expectations','econ_inflation',0.5],
['econ_inflation','econ_unemployment',0.6],
['econ_unemployment','econ_fiscal_multiplier',0.5],
['econ_fiscal_multiplier','econ_gdp',0.6],
['econ_gdp','econ_human_capital',0.5],
['econ_human_capital','econ_economies_scale',0.4],
['econ_gini','econ_pareto',0.4],
['econ_sunk_cost','econ_rational',0.5],
['econ_sunk_cost','econ_opportunity_cost',0.5]
// ===== ECON_TOPIC_THEORIES (append, key: [..]) =====
econ_monetary_policy: ['econ_new_classical','econ_monetarism'],
econ_fiscal_policy: ['econ_keynesian','econ_supply_side'],
econ_macro: ['econ_keynesian','econ_new_keynesian','econ_monetarism'],
econ_micro: ['econ_marginal','econ_general_eq'],
econ_industrial_org: ['econ_general_eq'],
econ_public_finance: ['econ_welfare','econ_supply_side'],
econ_development_field: ['econ_development_econ'],
econ_environmental_field: ['econ_environmental_econ'],
econ_health_econ: ['econ_welfare','econ_behavioral'],
econ_behavioral_finance: ['econ_behavioral'],
econ_banking: ['econ_monetarism','econ_new_classical'],
econ_taxation: ['econ_supply_side','econ_welfare']
// ===== CROSS_EDGES (append) =====
['econ_nash_eq','rational_choice',0.6],
['econ_gini','class_struggle',0.5],
['econ_thaler','psy_cognitive_bias',0.6],
['econ_malthus','conflict',0.4]
