// ===== PSY_THINKERS (append, comma-separated, no trailing comma needed) =====
{ id:'psy_james', name:'威廉·詹姆斯', en:'William James', years:'1842-1910', nationality:'美国', disc:'psy',
  bio:'美国心理学之父，功能主义创始人，倡导意识流与实用主义，著有《心理学原理》。',
  keyIdeas:['意识流','功能主义','实用主义'], influence:'psy_functionalism',
  works:['心理学原理','宗教经验种种','实用主义'],
  ideas:[ {t:'意识流', d:'意识不是离散元素的拼凑，而是连续流动、不断变化的整体。'},
          {t:'功能主义', d:'心理学应研究心智的用途与适应功能，而非只拆解其结构。'} ],
  wiki:'https://en.wikipedia.org/wiki/William_James' },
{ id:'psy_jung', name:'卡尔·荣格', en:'Carl Jung', years:'1875-1961', nationality:'瑞士', disc:'psy',
  bio:'分析心理学创始人，提出集体潜意识、原型与心理类型，著有《心理类型》《红书》。',
  keyIdeas:['集体潜意识','原型','心理类型','自性'], influence:'psy_analytical',
  works:['心理类型','原型与集体潜意识','红书'],
  ideas:[ {t:'集体潜意识', d:'人类共有的、超越个人经验的潜意识底层，内含普遍原型。'},
          {t:'原型', d:'集体潜意识中的普遍意象，如人格面具、阴影与自性。'} ],
  wiki:'https://en.wikipedia.org/wiki/Carl_Jung' },
{ id:'psy_adler', name:'阿尔弗雷德·阿德勒', en:'Alfred Adler', years:'1870-1937', nationality:'奥地利', disc:'psy',
  bio:'个体心理学创始人，强调自卑与补偿、追求优越与社会兴趣，著有《自卑与超越》。',
  keyIdeas:['自卑感','追求优越','社会兴趣','出生顺序'], influence:'psy_individual',
  works:['自卑与超越','个体心理学的理论与实践'],
  ideas:[ {t:'自卑与补偿', d:'人自婴儿期便有自卑感，并通过努力补偿来追求卓越。'},
          {t:'社会兴趣', d:'心理健康取决于对他人的关怀与稳固的社会归属感。'} ],
  wiki:'https://en.wikipedia.org/wiki/Alfred_Adler' },
{ id:'psy_erikson', name:'爱利克·埃里克森', en:'Erik Erikson', years:'1902-1994', nationality:'德裔美国', disc:'psy',
  bio:'心理社会发展八阶段理论提出者，强调一生身份认同的发展，著有《童年与社会》。',
  keyIdeas:['心理社会发展','身份认同','八阶段'], influence:'psy_psychosocial',
  works:['童年与社会','身份认同：青年与危机'],
  ideas:[ {t:'心理社会发展八阶段', d:'人一生经历八个阶段，每个阶段都有必须解决的发展冲突。'},
          {t:'身份认同危机', d:'青少年期的核心任务是建立稳定而连贯的自我身份。'} ],
  wiki:'https://en.wikipedia.org/wiki/Erik_Erikson' },
{ id:'psy_bowlby', name:'约翰·鲍尔比', en:'John Bowlby', years:'1907-1990', nationality:'英国', disc:'psy',
  bio:'依恋理论奠基人，强调婴儿与照顾者的情感联结及内部工作模型，著有《依恋与失落》。',
  keyIdeas:['依恋理论','内部工作模型','安全基地'], influence:'psy_attachment',
  works:['依恋与失落'],
  ideas:[ {t:'依恋理论', d:'婴儿与主要照顾者的情感联结是生存与发展的基础。'},
          {t:'内部工作模型', d:'早期依恋经验形成对自我与他人稳定的期待与信念。'} ],
  wiki:'https://en.wikipedia.org/wiki/John_Bowlby' },
{ id:'psy_ainsworth', name:'玛丽·安斯沃思', en:'Mary Ainsworth', years:'1913-1999', nationality:'加拿大裔美国', disc:'psy',
  bio:'通过陌生情境实验区分依恋类型，奠定依恋研究的实证基础。',
  keyIdeas:['陌生情境','依恋类型','安全型依恋'], influence:'psy_attachment',
  works:['依恋类型','陌生情境程序'],
  ideas:[ {t:'陌生情境实验', d:'通过分离与重聚系统观察婴儿依恋行为的经典方法。'},
          {t:'依恋类型', d:'区分安全型、焦虑-矛盾型与回避型等依恋模式。'} ],
  wiki:'https://en.wikipedia.org/wiki/Mary_Ainsworth' },
{ id:'psy_bandura', name:'阿尔伯特·班杜拉', en:'Albert Bandura', years:'1925-2021', nationality:'加拿大裔美国', disc:'psy',
  bio:'社会学习理论与自我效能提出者，著有《社会学习理论》《自我效能：控制的运用》。',
  keyIdeas:['观察学习','自我效能','相互决定论'], influence:'psy_social_learning',
  works:['社会学习理论','自我效能：控制的运用'],
  ideas:[ {t:'观察学习', d:'人通过观察与模仿他人行为来学习，不必亲身试误。'},
          {t:'自我效能', d:'对自己能否完成任务的信念，决定行动、努力与坚持。'} ],
  wiki:'https://en.wikipedia.org/wiki/Albert_Bandura' },
{ id:'psy_festinger', name:'利昂·费斯廷格', en:'Leon Festinger', years:'1919-1989', nationality:'美国', disc:'psy',
  bio:'认知失调理论与社会比较理论提出者，著有《认知失调理论》《当预言失灵》。',
  keyIdeas:['认知失调','社会比较','决策后失调'], influence:'psy_dissonance',
  works:['认知失调理论','当预言失灵'],
  ideas:[ {t:'认知失调', d:'当态度与行为冲突时产生心理紧张，驱使人改变以恢复一致。'},
          {t:'社会比较理论', d:'人通过与他人比较来评估自己的能力与他人观点。'} ],
  wiki:'https://en.wikipedia.org/wiki/Leon_Festinger' },
{ id:'psy_beck', name:'亚伦·贝克', en:'Aaron Beck', years:'1921-2021', nationality:'美国', disc:'psy',
  bio:'认知疗法（CBT前身）创始人，提出认知三角与自动思维，著有《抑郁症》。',
  keyIdeas:['认知三角','自动思维','认知重构'], influence:'psy_cbt',
  works:['抑郁症','认知疗法与情绪障碍'],
  ideas:[ {t:'自动思维', d:'引发情绪困扰的、未经审视的即时想法。'},
          {t:'认知重构', d:'识别并挑战扭曲思维，以改变情绪与行为。'} ],
  wiki:'https://en.wikipedia.org/wiki/Aaron_Beck' },
{ id:'psy_ellis', name:'阿尔伯特·艾利斯', en:'Albert Ellis', years:'1913-2007', nationality:'美国', disc:'psy',
  bio:'理性情绪行为疗法（REBT）创始人，提出ABC模型，著有《理性生活指南》。',
  keyIdeas:['ABC模型','非理性信念','REBT'], influence:'psy_cbt',
  works:['理性生活指南','理性情绪行为疗法'],
  ideas:[ {t:'ABC模型', d:'事件(A)经信念(B)引发情绪后果(C)，改变信念即可改变情绪。'},
          {t:'非理性信念', d:'绝对化、灾难化的要求是造成情绪困扰的根源。'} ],
  wiki:'https://en.wikipedia.org/wiki/Albert_Ellis' },
{ id:'psy_neisser', name:'乌尔里克·奈瑟', en:'Ulric Neisser', years:'1928-2012', nationality:'美国', disc:'psy',
  bio:'被誉为认知心理学之父，1967年出版《认知心理学》确立该学科范式。',
  keyIdeas:['认知心理学','生态效度','记忆重构'], influence:'psy_cognitive',
  works:['认知心理学','认知与现实'],
  ideas:[ {t:'认知心理学', d:'将心智视为信息加工系统，研究注意、记忆、知觉与语言。'},
          {t:'生态效度', d:'批评实验室记忆研究脱离真实生活情境。'} ],
  wiki:'https://en.wikipedia.org/wiki/Ulric_Neisser' },
{ id:'psy_loftus', name:'伊丽莎白·洛夫特斯', en:'Elizabeth Loftus', years:'1944-', nationality:'美国', disc:'psy',
  bio:'研究错误记忆与目击者证词，揭示记忆可被误导信息改写。',
  keyIdeas:['错误记忆','误导信息效应','目击者证词'], influence:'psy_cognitive',
  works:['目击者证词','记忆的错误'],
  ideas:[ {t:'错误记忆', d:'人的记忆可被误导信息改写，并非录像式准确。'},
          {t:'误导信息效应', d:'事后不实信息会污染并改变原有记忆。'} ],
  wiki:'https://en.wikipedia.org/wiki/Elizabeth_Loftus' },
{ id:'psy_seligman', name:'马丁·塞利格曼', en:'Martin Seligman', years:'1942-', nationality:'美国', disc:'psy',
  bio:'发现习得性无助并倡导积极心理学，提出PERMA幸福模型，著有《真实的幸福》。',
  keyIdeas:['习得性无助','积极心理学','PERMA模型'], influence:'psy_positive',
  works:['习得性无助','真实的幸福'],
  ideas:[ {t:'习得性无助', d:'反复受挫后即使有出路也放弃尝试的被动状态。'},
          {t:'积极心理学', d:'研究幸福、优势与人的蓬勃发展，而非仅治疗疾病。'} ],
  wiki:'https://en.wikipedia.org/wiki/Martin_Seligman' },
{ id:'psy_gardner', name:'霍华德·加德纳', en:'Howard Gardner', years:'1943-', nationality:'美国', disc:'psy',
  bio:'多元智能理论提出者，反对单一智商观，著有《心智的框架》。',
  keyIdeas:['多元智能','八种智能','反智商中心'], influence:'psy_multi_intelligence',
  works:['心智的框架','多元智能新视野'],
  ideas:[ {t:'多元智能', d:'智力不是单一能力，而是语言、逻辑、空间等多种相对独立的智能。'},
          {t:'智能多元观', d:'教育应尊重个体不同的智能组合与优势。'} ],
  wiki:'https://en.wikipedia.org/wiki/Howard_Gardner' },
{ id:'psy_tversky', name:'阿莫斯·特沃斯基', en:'Amos Tversky', years:'1937-1996', nationality:'以色列裔美国', disc:'psy',
  bio:'与卡尼曼共创前景理论，揭示启发式与偏差，奠定行为决策研究。',
  keyIdeas:['前景理论','启发式与偏差','框架效应'], influence:'psy_prospect',
  works:['前景理论','不确定下的判断'],
  ideas:[ {t:'前景理论', d:'人对得失偏好不对称，损失带来的痛苦大于等额收益。'},
          {t:'启发式与偏差', d:'人在不确定下用简便启发式，却会系统性偏离理性。'} ],
  wiki:'https://en.wikipedia.org/wiki/Amos_Tversky' },
{ id:'psy_lewin', name:'库尔特·勒温', en:'Kurt Lewin', years:'1890-1947', nationality:'德裔美国', disc:'psy',
  bio:'格式塔心理学家、社会心理学之父，提出场论与群体动力学。',
  keyIdeas:['场论','群体动力学','力场分析'], influence:'psy_gestalt',
  works:['拓扑心理学原理','解决社会冲突'],
  ideas:[ {t:'场论', d:'行为是人及其心理环境场的函数，B=f(P,E)。'},
          {t:'群体动力学', d:'群体如同一动态场，成员互动改变整体行为。'} ],
  wiki:'https://en.wikipedia.org/wiki/Kurt_Lewin' },
{ id:'psy_allport', name:'戈登·奥尔波特', en:'Gordon Allport', years:'1897-1967', nationality:'美国', disc:'psy',
  bio:'特质心理学奠基人，提出人格特质理论与机能自主性，著有《偏见的本质》。',
  keyIdeas:['特质理论','机能自主性','首因效应'], influence:'psy_trait',
  works:['人格：心理学的解释','偏见的本质'],
  ideas:[ {t:'特质理论', d:'人格由相对稳定的特质维度构成，可描述个体差异。'},
          {t:'机能自主性', d:'成人的动机可独立于其最初成因而独立运作。'} ],
  wiki:'https://en.wikipedia.org/wiki/Gordon_Allport' }
// ===== PSY_THEORIES =====
{ id:'psy_functionalism', name:'功能主义', en:'Functionalism', era:'classical', disc:'psy',
  desc:'主张心理学应研究心智如何帮助有机体适应环境。',
  detail:'兴起于19世纪末的美国，以威廉·詹姆斯为代表，反对冯特的元素分析法，强调心理过程的用途与目的。它把心智视为协助生存与适应的工具，为应用心理学奠定基础。',
  meaning:'别问心是什么，先问心有什么用。',
  keyThinkers:['psy_james'], concepts:[],
  wiki:'https://en.wikipedia.org/wiki/Functionalism_(psychology)' },
{ id:'psy_gestalt', name:'格式塔心理学', en:'Gestalt psychology', era:'classical', disc:'psy',
  desc:'主张知觉经验是整体大于部分之和。',
  detail:'20世纪初发端于德国，强调人对形状的完形组织原则（如接近性、相似性、闭合）。勒温将其场论思想引入社会与动机研究。',
  meaning:'看森林，别只数树木。',
  keyThinkers:['psy_lewin'], concepts:[],
  wiki:'https://en.wikipedia.org/wiki/Gestalt_psychology' },
{ id:'psy_analytical', name:'分析心理学', en:'Analytical psychology', era:'classical', disc:'psy',
  desc:'荣格创立的心理学派，聚焦集体潜意识与个体化。',
  detail:'与弗洛伊德分道扬镳后，荣格提出集体潜意识、原型与心理类型，强调一生中自性化的心灵整合过程。',
  meaning:'每个人的内心都携带着人类共有的古老意象。',
  keyThinkers:['psy_jung'], concepts:['psy_collective_unconscious','psy_archetype'],
  wiki:'https://en.wikipedia.org/wiki/Analytical_psychology' },
{ id:'psy_individual', name:'个体心理学', en:'Individual psychology', era:'classical', disc:'psy',
  desc:'阿德勒创立的学派，强调自卑、补偿与社会兴趣。',
  detail:'阿德勒认为人自婴儿期便有自卑感，通过追求优越来补偿；心理健康取决于社会兴趣与对他人的归属感。',
  meaning:'人不为过去所困，而为目标与意义所驱。',
  keyThinkers:['psy_adler'], concepts:[],
  wiki:'https://en.wikipedia.org/wiki/Individual_psychology' },
{ id:'psy_psychosocial', name:'心理社会发展理论', en:'Psychosocial development', era:'structural', disc:'psy',
  desc:'埃里克森提出的一生八个发展阶段模型。',
  detail:'在弗洛伊德心理性阶段基础上，埃里克森以社会文化视角提出信任对不信任等八对冲突，每一阶段成功解决才能健康发展。',
  meaning:'一生都在回答我谁、我属于哪的问题。',
  keyThinkers:['psy_erikson'], concepts:['psy_attachment_styles'],
  wiki:'https://en.wikipedia.org/wiki/Erikson%27s_stages_of_psychosocial_development' },
{ id:'psy_cognitive', name:'认知心理学', en:'Cognitive psychology', era:'structural', disc:'psy',
  desc:'将心智视为信息加工系统的现代心理学分支。',
  detail:'20世纪50年代后兴起，受奈瑟《认知心理学》推动，研究注意、知觉、记忆、语言与问题解决。它把人脑类比计算机，关注内部心理表征。',
  meaning:'心智是一台会出错的生物计算机。',
  keyThinkers:['psy_neisser','psy_loftus'], concepts:['psy_working_memory','psy_longterm_memory','psy_schema','psy_priming'],
  wiki:'https://en.wikipedia.org/wiki/Cognitive_psychology' },
{ id:'psy_cbt', name:'认知行为疗法', en:'Cognitive behavioral therapy', era:'critical', disc:'psy',
  desc:'通过改变认知与行为来缓解心理困扰的心理治疗。',
  detail:'由贝克与艾利斯在20世纪中后期发展，主张情绪困扰源于扭曲思维与适应不良行为，通过认知重构与行为训练实现改变。',
  meaning:'改不了世界，就改你看待世界的想法。',
  keyThinkers:['psy_beck','psy_ellis'], concepts:['psy_learned_helplessness'],
  wiki:'https://en.wikipedia.org/wiki/Cognitive_behavioral_therapy' },
{ id:'psy_positive', name:'积极心理学', en:'Positive psychology', era:'contemporary', disc:'psy',
  desc:'研究幸福、优势与人类蓬勃发展的心理学运动。',
  detail:'由塞利格曼在1998年前后倡导，把心理学重心从治病扩展到培养美德、心流与意义，提出PERMA幸福模型。',
  meaning:'心理学不该只修残补缺，也要让人开花。',
  keyThinkers:['psy_seligman'], concepts:['psy_flow'],
  wiki:'https://en.wikipedia.org/wiki/Positive_psychology' },
{ id:'psy_multi_intelligence', name:'多元智能理论', en:'Theory of multiple intelligences', era:'contemporary', disc:'psy',
  desc:'加德纳提出智力由多种相对独立的智能构成。',
  detail:'反对单一智商观，主张语言、逻辑-数学、空间、音乐、身体、人际、内省、自然观察等智能各自发展，教育应因材施教。',
  meaning:'聪明不止一种写法。',
  keyThinkers:['psy_gardner'], concepts:['psy_emotional_intelligence'],
  wiki:'https://en.wikipedia.org/wiki/Theory_of_multiple_intelligences' },
{ id:'psy_dissonance', name:'认知失调理论', en:'Cognitive dissonance', era:'critical', disc:'psy',
  desc:'费斯廷格提出态度与行为冲突会产生心理紧张。',
  detail:'当人同时持有不一致的认知或行为违背信念时，会产生不适并驱使其改变态度、行为或合理化，以恢复认知一致。',
  meaning:'嘴上说不要，身体很诚实，于是大脑开始编故事。',
  keyThinkers:['psy_festinger'], concepts:['psy_cognitive_dissonance'],
  wiki:'https://en.wikipedia.org/wiki/Cognitive_dissonance' },
{ id:'psy_trait', name:'特质理论', en:'Trait theory', era:'critical', disc:'psy',
  desc:'用稳定的特质维度描述人格个体差异。',
  detail:'以奥尔波特、卡特尔、艾森克为代表，主张人格由跨情境稳定的特质构成，后发展为大五人格模型，用五个维度刻画所有人。',
  meaning:'你是谁，藏在那些反复出现的习惯里。',
  keyThinkers:['psy_allport'], concepts:['psy_big_five'],
  wiki:'https://en.wikipedia.org/wiki/Trait_theory' }
// ===== PSY_CONCEPTS =====
{ id:'psy_working_memory', name:'工作记忆', en:'Working memory', disc:'psy',
  desc:'用于在短时内暂存并操作信息的记忆系统。',
  detail:'有别于被动的短时记忆，工作记忆能同时保持与加工信息，如心算时记数字并运算。巴德利提出其包含语音环、视空间模板与中央执行系统。',
  example:'边听电话边在脑中复述对方的账号数字，就是工作记忆在干活。',
  wiki:'https://en.wikipedia.org/wiki/Working_memory' },
{ id:'psy_longterm_memory', name:'长时记忆', en:'Long-term memory', disc:'psy',
  desc:'可长期保持大量信息的记忆仓库。',
  detail:'容量近乎无限，分为陈述性（事实与事件）与程序性（技能与习惯）记忆。其形成依赖海马体与神经可塑性。',
  example:'你至今记得小时候家的住址，便是长时记忆。',
  wiki:'https://en.wikipedia.org/wiki/Long-term_memory' },
{ id:'psy_schema', name:'图式', en:'Schema', disc:'psy',
  desc:'组织知识的心理框架，用于理解与预测世界。',
  detail:'皮亚杰认为图式是认知结构，通过同化与顺应随经验发展；认知心理学中图式帮助快速解释信息，却也造成偏见。',
  example:'你脑中餐厅的图式让你一进门就找服务员、看菜单，无需重新学习。',
  wiki:'https://en.wikipedia.org/wiki/Schema_(psychology)' },
{ id:'psy_self_efficacy', name:'自我效能', en:'Self-efficacy', disc:'psy',
  desc:'对自己能否完成特定任务的信念。',
  detail:'班杜拉提出，自我效能影响人是否尝试、投入多少努力以及面对挫折能坚持多久，是动机与行为改变的核心。',
  example:'相信自己能跑完5公里的人，更可能真的开始训练并坚持。',
  wiki:'https://en.wikipedia.org/wiki/Self-efficacy' },
{ id:'psy_learned_helplessness', name:'习得性无助', en:'Learned helplessness', disc:'psy',
  desc:'反复受挫后即使有机会也放弃尝试的状态。',
  detail:'塞利格曼通过狗的电击实验发现，当结果不可控时，有机体会学会被动；这被用来解释人类抑郁与动机丧失。',
  example:'考试屡屡失利后，学生便不再复习，哪怕题目已变简单。',
  wiki:'https://en.wikipedia.org/wiki/Learned_helplessness' },
{ id:'psy_flow', name:'心流', en:'Flow', disc:'psy',
  desc:'完全沉浸、忘我且高效的活动状态。',
  detail:'契克森米哈伊提出，当挑战与技能匹配、目标明确且反馈即时时，人进入忘我专注、时间感扭曲的最佳体验。',
  example:'画家连续作画数小时却感觉只过了几分钟，便是心流。',
  wiki:'https://en.wikipedia.org/wiki/Flow_(psychology)' },
{ id:'psy_growth_mindset', name:'成长型思维', en:'Growth mindset', disc:'psy',
  desc:'相信能力可通过努力成长的信念。',
  detail:'德韦克提出，与固定型思维相对，成长型思维者把失败看作学习机会，更愿接受挑战并坚持，成绩与韧性更好。',
  example:'被批评后想“我还没学会”而非“我不行”的孩子，更可能进步。',
  wiki:'https://en.wikipedia.org/wiki/Mindset' },
{ id:'psy_emotional_intelligence', name:'情绪智力', en:'Emotional intelligence', disc:'psy',
  desc:'识别、理解并管理自己与他人情绪的能力。',
  detail:'萨洛维与梅耶提出、戈尔曼推广，包含情绪觉察、情绪调节、共情与人际技能，被认为能预测生活成功。',
  example:'同事发火时你能先安抚再谈事，就是高情绪智力。',
  wiki:'https://en.wikipedia.org/wiki/Emotional_intelligence' },
{ id:'psy_big_five', name:'大五人格', en:'Big Five personality traits', disc:'psy',
  desc:'用五个维度描述人格的通用模型。',
  detail:'即开放性、尽责性、外向性、宜人性、神经质（OCEAN），跨文化稳定，能预测工作、关系等多方面表现。',
  example:'一个高尽责低神经质的人通常靠谱且情绪平稳。',
  wiki:'https://en.wikipedia.org/wiki/Big_Five_personality_traits' },
{ id:'psy_defense', name:'心理防御机制', en:'Defense mechanisms', disc:'psy',
  desc:'自我用来缓解焦虑的无意识策略。',
  detail:'弗洛伊德与安娜·弗洛伊德提出，如压抑、投射、升华等，短期保护自尊，过度使用则扭曲现实。',
  example:'把对老板的愤怒升华成加倍工作，就是一种防御机制。',
  wiki:'https://en.wikipedia.org/wiki/Defence_mechanism' },
{ id:'psy_id_ego_superego', name:'本我自我超我', en:'Id, ego and superego', disc:'psy',
  desc:'弗洛伊德人格结构的三部分模型。',
  detail:'本我遵循快乐原则、自我遵循现实原则、超我代表道德规范；三者冲突与平衡决定行为与症状。',
  example:'想暴食的是本我，劝你节制的是超我，最后决定吃一半的是自我。',
  wiki:'https://en.wikipedia.org/wiki/Id,_ego_and_superego' },
{ id:'psy_collective_unconscious', name:'集体潜意识', en:'Collective unconscious', disc:'psy',
  desc:'荣格提出的人类共有的潜意识层面。',
  detail:'区别于个人潜意识，它包含人类演化的普遍经验与意象，是所有人都继承的心理底层结构。',
  example:'不同文化都有智慧老人、英雄这类原型形象，便源于集体潜意识。',
  wiki:'https://en.wikipedia.org/wiki/Collective_unconscious' },
{ id:'psy_archetype', name:'原型', en:'Archetype', disc:'psy',
  desc:'集体潜意识中的普遍意象与模式。',
  detail:'荣格认为原型是先天的心理倾向，如人格面具、阴影、自性、英雄，体现在神话、梦与艺术中。',
  example:'童话里继母是恶人、小矮人助你的套路，是跨越文化的原型。',
  wiki:'https://en.wikipedia.org/wiki/Jungian_archetypes' },
{ id:'psy_intrinsic', name:'内在动机', en:'Intrinsic motivation', disc:'psy',
  desc:'因活动本身有趣或有意义而行动的动力。',
  detail:'与外在奖励相对，内在动机带来更深投入与持久坚持，是自主学习、创造与心流的重要来源。',
  example:'有人纯粹因为喜欢而弹琴，不图演出报酬，就是内在动机。',
  wiki:'https://en.wikipedia.org/wiki/Intrinsic_motivation' },
{ id:'psy_extrinsic', name:'外在动机', en:'Extrinsic motivation', disc:'psy',
  desc:'为外部奖励或避免惩罚而行动的动力。',
  detail:'来自金钱、分数、称赞或恐惧等外部后果；过度使用可能削弱内在动机（过度辩护效应）。',
  example:'为拿奖学金而读书，是典型的外在动机。',
  wiki:'https://en.wikipedia.org/wiki/Extrinsic_motivation' },
{ id:'psy_confirmation_bias', name:'确认偏误', en:'Confirmation bias', disc:'psy',
  desc:'人倾向于搜寻支持既有信念的信息。',
  detail:'人会更多注意、记住和采信符合自己观点的证据，忽略反例，导致信念固化与群体极化。',
  example:'坚信某疗法有效的人，只转发成功案例，无视失败数据。',
  wiki:'https://en.wikipedia.org/wiki/Confirmation_bias' },
{ id:'psy_availability', name:'可得性启发', en:'Availability heuristic', disc:'psy',
  desc:'以容易想到的例子来判断事件概率。',
  detail:'特沃斯基与卡尼曼提出，人对易回忆的事件高估其频率，导致对罕见风险的误判。',
  example:'刚看过空难新闻就觉得坐飞机很危险，其实远不如开车常见。',
  wiki:'https://en.wikipedia.org/wiki/Availability_heuristic' },
{ id:'psy_fae', name:'基本归因错误', en:'Fundamental attribution error', disc:'psy',
  desc:'高估个性、低估情境对他人行为的解释。',
  detail:'解释他人行为时，人常归因于其性格而非环境因素，例如把别人迟到归为不靠谱而非堵车。',
  example:'看到路人摔跤先笑他笨，却没注意地上香蕉皮。',
  wiki:'https://en.wikipedia.org/wiki/Fundamental_attribution_error' },
{ id:'psy_in_out_group', name:'内群体外群体', en:'In-group and out-group', disc:'psy',
  desc:'人把社会分为自己人与外人的倾向。',
  detail:'对内群体偏袒、对外群体敌视或贬低，是社会认同、偏见与刻板印象的心理根源。',
  example:'球迷为本队犯规找借口、却苛责对手同样动作，就是内外群体效应。',
  wiki:'https://en.wikipedia.org/wiki/In-group_and_out-group' },
{ id:'psy_priming', name:'启动效应', en:'Priming', disc:'psy',
  desc:'先前刺激无意识地影响后续反应的现象。',
  detail:'在语义或知觉上激活相关概念后，人对相关信息的加工会变快，体现记忆与联想的自动扩散。',
  example:'先看到医生再看护士会反应更快，因为概念被启动了。',
  wiki:'https://en.wikipedia.org/wiki/Priming_(psychology)' },
{ id:'psy_neuroplasticity', name:'神经可塑性', en:'Neuroplasticity', disc:'psy',
  desc:'大脑结构与功能随经验改变的能力。',
  detail:'神经元连接可因学习、训练或损伤而重组，贯穿一生，是记忆、康复与发育的生理基础。',
  example:'盲人的听觉皮层会接管视觉区，变得更敏锐。',
  wiki:'https://en.wikipedia.org/wiki/Neuroplasticity' },
{ id:'psy_attachment_styles', name:'依恋类型', en:'Attachment styles', disc:'psy',
  desc:'婴儿与照顾者形成的稳定情感联结模式。',
  detail:'安斯沃思经陌生情境实验区分安全型、焦虑-矛盾型与回避型；成人亲密关系中也浮现类似模式，影响信任与亲密。',
  example:'安全型的人在伴侣离开时能安抚自己，重聚时自然亲近。',
  wiki:'https://en.wikipedia.org/wiki/Attachment_theory' }
// ===== PSY_TOPICS =====
{ id:'psy_memory', name:'记忆', en:'Memory', disc:'psy',
  desc:'对信息进行编码、存储与提取的心理能力。',
  detail:'记忆分为感觉、短时工作与长时记忆，受注意、复述与情绪影响，且可被误导与重构。',
  wiki:'https://en.wikipedia.org/wiki/Memory' },
{ id:'psy_learning', name:'学习', en:'Learning', disc:'psy',
  desc:'经验导致的行为或认知的相对持久改变。',
  detail:'包括经典条件反射、操作条件反射与观察学习，是发展、教育与行为改变的核心过程。',
  wiki:'https://en.wikipedia.org/wiki/Learning' },
{ id:'psy_perception', name:'知觉', en:'Perception', disc:'psy',
  desc:'大脑组织感官信息形成有意义的经验。',
  detail:'知觉并非被动接收，而是主动建构，受注意、期望与格式塔组织原则影响，常出现错觉。',
  wiki:'https://en.wikipedia.org/wiki/Perception' },
{ id:'psy_developmental', name:'发展心理学', en:'Developmental psychology', disc:'psy',
  desc:'研究人从出生到老年的心理变化。',
  detail:'关注认知、情绪与社会性的年龄规律与关键期，涵盖皮亚杰、维果茨基与埃里克森等理论。',
  wiki:'https://en.wikipedia.org/wiki/Developmental_psychology' },
{ id:'psy_cognitive_field', name:'认知心理学（学科）', en:'Cognitive psychology (field)', disc:'psy',
  desc:'研究心智如何加工信息的心理学分支。',
  detail:'涵盖注意、知觉、记忆、语言、推理与决策，是当代心理学的主流范式之一。',
  wiki:'https://en.wikipedia.org/wiki/Cognitive_psychology' },
{ id:'psy_clinical', name:'临床心理学', en:'Clinical psychology', disc:'psy',
  desc:'评估、诊断与治疗心理障碍的应用领域。',
  detail:'结合科学研究与临床实践，运用心理治疗（如CBT）与心理测评，区别于精神医学的药物治疗。',
  wiki:'https://en.wikipedia.org/wiki/Clinical_psychology' },
{ id:'psy_positive_field', name:'积极心理学（领域）', en:'Positive psychology (field)', disc:'psy',
  desc:'研究幸福、优势与人类潜能的心理学分支。',
  detail:'关注情绪、投入、关系、意义与成就，致力于提升个人与群体的福祉。',
  wiki:'https://en.wikipedia.org/wiki/Positive_psychology' },
{ id:'psy_neuroscience', name:'生理心理学与神经科学', en:'Biological psychology', disc:'psy',
  desc:'从脑与生理机制解释心理与行为。',
  detail:'研究神经元、神经递质、脑区功能与激素如何支撑感知、情绪、学习与精神疾患，依赖脑成像等技术。',
  wiki:'https://en.wikipedia.org/wiki/Biological_psychology' },
{ id:'psy_motivation', name:'动机', en:'Motivation', disc:'psy',
  desc:'驱动、导向与维持行为的内部动力。',
  detail:'可分为内在与外在动机，受需求、目标、期望与自我决定等因素影响，解释人为什么做某事。',
  wiki:'https://en.wikipedia.org/wiki/Motivation' },
{ id:'psy_intelligence', name:'智力', en:'Intelligence', disc:'psy',
  desc:'学习、推理与适应环境的能力。',
  detail:'传统以智商测量，多元智能与流体晶体智力等理论挑战了单一智力观，涉及遗传与环境之争。',
  wiki:'https://en.wikipedia.org/wiki/Intelligence' },
{ id:'psy_psychotherapy', name:'心理治疗', en:'Psychotherapy', disc:'psy',
  desc:'通过心理方法缓解困扰、促进改变的专业过程。',
  detail:'流派众多，包括精神分析、人本、认知行为与家庭治疗等，效果取决于方法匹配与咨访关系。',
  wiki:'https://en.wikipedia.org/wiki/Psychotherapy' },
{ id:'psy_stress', name:'压力与应对', en:'Stress and coping', disc:'psy',
  desc:'个体面对挑战时的生理心理反应与调节。',
  detail:'拉扎勒斯提出应激是人与环境的评价交互；长期压力损害健康，应对方式包括问题聚焦与情绪聚焦。',
  wiki:'https://en.wikipedia.org/wiki/Stress_(psychological)' }
// ===== THINKER_LINKS (append) =====
['psy_jung','psy_freud',0.7],
['psy_adler','psy_freud',0.6],
['psy_erikson','psy_freud',0.6],
['psy_erikson','psy_piaget',0.7],
['psy_bowlby','psy_ainsworth',0.9],
['psy_bowlby','psy_freud',0.5],
['psy_bandura','psy_skinner',0.7],
['psy_bandura','psy_festinger',0.5],
['psy_festinger','psy_lewin',0.7],
['psy_lewin','psy_allport',0.5],
['psy_beck','psy_ellis',0.9],
['psy_beck','psy_freud',0.5],
['psy_ellis','psy_freud',0.5],
['psy_neisser','psy_piaget',0.6],
['psy_neisser','psy_loftus',0.8],
['psy_seligman','psy_beck',0.6],
['psy_seligman','psy_maslow',0.7],
['psy_gardner','psy_neisser',0.5],
['psy_tversky','psy_kahneman',0.9],
['psy_allport','psy_freud',0.5],
['psy_erikson','psy_bowlby',0.5],
['psy_jung','psy_adler',0.6]
// ===== CONCEPT_LINKS (append) =====
['psy_working_memory','psy_longterm_memory',0.8],
['psy_working_memory','psy_schema',0.6],
['psy_longterm_memory','psy_neuroplasticity',0.7],
['psy_longterm_memory','psy_schema',0.6],
['psy_schema','psy_priming',0.6],
['psy_priming','psy_cognitive_dissonance',0.5],
['psy_self_efficacy','psy_learned_helplessness',0.7],
['psy_self_efficacy','psy_intrinsic',0.6],
['psy_self_efficacy','psy_growth_mindset',0.6],
['psy_learned_helplessness','psy_self_actual',0.5],
['psy_learned_helplessness','psy_growth_mindset',0.5],
['psy_flow','psy_intrinsic',0.7],
['psy_flow','psy_self_actual',0.6],
['psy_emotional_intelligence','psy_self_actual',0.6],
['psy_emotional_intelligence','psy_big_five',0.5],
['psy_big_five','psy_self_actual',0.5],
['psy_defense','psy_id_ego_superego',0.8],
['psy_defense','psy_unconscious',0.7],
['psy_id_ego_superego','psy_unconscious',0.8],
['psy_id_ego_superego','psy_collective_unconscious',0.5],
['psy_collective_unconscious','psy_archetype',0.9],
['psy_archetype','psy_unconscious',0.5],
['psy_intrinsic','psy_extrinsic',0.8],
['psy_intrinsic','psy_needs',0.5],
['psy_extrinsic','psy_needs',0.5],
['psy_confirmation_bias','psy_availability',0.7],
['psy_confirmation_bias','psy_cognitive_dissonance',0.6],
['psy_availability','psy_loss_aversion',0.5],
['psy_fae','psy_stereotype',0.6],
['psy_fae','psy_in_out_group',0.6],
['psy_in_out_group','psy_stereotype',0.8],
['psy_in_out_group','psy_bystander',0.5],
['psy_attachment_styles','psy_psych_safety',0.6],
['psy_neuroplasticity','psy_schema',0.5]
// ===== PSY_TOPIC_THEORIES (append, key: [..]) =====
psy_memory: ['psy_cognitive','psy_cognitive_dev'],
psy_learning: ['psy_behaviorism','psy_social_learning'],
psy_perception: ['psy_gestalt','psy_cognitive'],
psy_developmental: ['psy_psychosocial','psy_cognitive_dev'],
psy_cognitive_field: ['psy_cognitive','psy_gestalt'],
psy_clinical: ['psy_cbt','psy_psychoanalysis'],
psy_positive_field: ['psy_positive'],
psy_neuroscience: ['psy_cognitive'],
psy_motivation: ['psy_humanistic','psy_behaviorism'],
psy_intelligence: ['psy_multi_intelligence','psy_trait'],
psy_psychotherapy: ['psy_cbt','psy_psychoanalysis'],
psy_stress: ['psy_cbt','psy_humanistic']
// ===== CROSS_EDGES (append) =====
['psy_tversky','econ_behavioral',0.7],
['psy_bandura','socialization',0.5],
['psy_erikson','socialization',0.6],
['psy_festinger','self_presentation',0.5]
